Side nav
WilderDev/WATT-Angular-Dashboard pull request #31
Opened 2022-01-27 15:40 UTC by Tkanscholl

can someone look at this and see why the routerlink isnt working

2022-01-27 15:43 UTC, lilysmith1206 requested changes

2022-01-27 15:43 UTC, lilysmith1206 commented on src/app/side-nav/side-nav.component.html
> +       <h3> <a routerlink="'/login'">Login</a></h3>
You're passing in the value `'/login'` to navigated to, instead of `/login/`

2022-01-28 00:21 UTC, Tkanscholl commented on src/app/side-nav/side-nav.component.html
> +       <h3> <a routerlink="'/login'">Login</a></h3>
it is now updated

2022-01-28 00:24 UTC, ZeldaMazzy approved these changes
Looks good to me

2022-01-28 00:25 UTC, thinhnguyen2411vn approved these changes

2022-01-28 00:42 UTC, merged