Side nav
WilderDev/WATT-Angular-Dashboard pull request #6
Opened 2022-01-11 01:02 UTC by Tkanscholl

updated

2022-01-11 01:07 UTC, WilderDev submitted a review, later dismissed

2022-01-11 01:27 UTC, ZeldaMazzy requested changes
In the side-nav html page, there are a few tags that are not closed out. Be sure to close your tags out.

Swap 'ul' with 'li' in your CSS page

In 'font-family', add the following line after the font name (in case for some reason users cannot display the required fonts, this goes for mr eaves & montserrat): Helvetica, Arial, sans-serif

2022-01-13 02:41 UTC, ZeldaMazzy submitted a review, later dismissed

2022-01-13 23:48 UTC, ZeldaMazzy approved these changes

2022-01-13 23:48 UTC, merged