added auth comp basics
WilderDev/WATT-Angular-Dashboard pull request #9
Opened 2022-01-11 01:41 UTC by JCalhoun95

added auth component

2022-01-11 03:08 UTC, Tkanscholl submitted a review, later dismissed

2022-01-11 04:31 UTC, ZeldaMazzy requested changes
Everything looks really good so far. Only a couple of changes first before moving forward:

Password fields need to be type="password" instead of text

Be mode descriptive for the form ref, instead of #templateFormRef, name it something like #loginRef, etc

Suggest leaving no spaces in ID's and Name fields in the inputs, and instead use dashes or camel case

2022-01-13 23:19 UTC, Tkanscholl approved these changes

2022-01-13 23:48 UTC, lilysmith1206 requested changes

2022-01-13 23:48 UTC, lilysmith1206 commented on src/app/auth-comp/sign-up/sign-up.component.html
> +      <label for="event name">Event Name :</label>
Inconsistent naming convention: `for="lastName"` earlier, `for="event name"` now. Change to `eventName`.

2022-01-13 23:48 UTC, merged